// Live source of the question data shown in the app. Loaded by index.html via a
// plain <script src="./prompts.js"> tag in <head>, before the app's own script
// runs — edit the questions below and refresh the page to see the changes.
//
// Each question's "aiOptimised" text is its core prompt. The answer style the
// user picks is not part of it: the matching "styleBlocks" text is added to the
// bottom of the prompt when it is copied or launched.
//
// Each question's "topics" lists the answers it is offered under in the site's
// shortlisting questions, by the ids in "shortlist" below. A question tagged
// "help" is offered under every answer. "stages" is the same information by
// stage alone, which the optimiser shows beside each question. A question marked
// "archived" is kept for its id and history but is not shown on the site.
//
// "shortlist" holds the wording of the first two shortlisting questions and of
// their answers. The ids must not change: the questions' "topics" refer to them.
//
// This file is edited from the optimiser's "Edit questions" page, which checks
// it and keeps a copy of the old file. It can still be edited by hand.
window.PROMPTS_DATA = {
  "styleBlocks": {
    "caseStudy": { "label": "In the style of real world case studies", "text": "How to present your answer:\nFor each question, explain it through one or two short worked examples of believable people in the UK, with ages and circumstances I could recognise. Show what they had, what they chose and what happened, then what that shows in general, with no separate explanation. Say plainly that they are illustrations, not real people and not recommendations for me. Keep figures simple, and check they add up. This is only about how you present the answer: everything else I have asked for still applies." },
    "factual": { "label": "With numbers and facts", "text": "How to present your answer:\nFor each question, put the key numbers and facts first, in short bullet points or a small table, with little narrative around them. Say which tax year every figure is for and where I can check it. Label estimates and assumptions and keep them apart from facts. Where you work something out, show the steps. Say when you are unsure of a figure rather than guess. This is only about how you present the answer: everything else I have asked for still applies." },
    "simple": { "label": "Short and simple descriptions", "text": "How to present your answer:\nKeep it short and simple, as you would for a friend. Put the main point first. Use everyday words and short sentences, and explain any pension term in plain words the first time you use it. Use no more than five bullet points for each question and leave out detail I did not ask for. I should be able to take it in at one reading. This is only about how you present the answer: everything else I have asked for still applies." }
  },
  "shortlist": {
    "stageQuestion": "Where are you in your retirement income planning?",
    "topicQuestion": "What do you want to know?",
    "helpHeading": "Where to get help",
    "stages": [
      { "id": "building", "label": "Still building up towards retirement", "topics": [
        { "id": "building_have", "label": "What I have and what I might get" },
        { "id": "building_need", "label": "How much I need and how to get there" },
        { "id": "building_change", "label": "What could change my plans" }
      ] },
      { "id": "soon", "label": "Thinking about retiring soon", "topics": [
        { "id": "soon_get", "label": "What I will get and whether it is enough" },
        { "id": "soon_options", "label": "My options for taking my pension" },
        { "id": "soon_sort", "label": "What to sort out before I retire" }
      ] },
      { "id": "taking", "label": "I'm already taking income", "topics": [
        { "id": "taking_last", "label": "Making my money last" },
        { "id": "taking_tax", "label": "Paying less tax and making more of what I have" },
        { "id": "taking_later", "label": "Planning for later life and my family" }
      ] }
    ]
  },
  "sections": [
    {
      "id": "foundation",
      "title": "Foundations of a plan",
      "subtitle": "The essential building blocks everyone needs to understand first.",
      "questions": [
        { "id": "foundation_6", "quickSummary": "Type of pension", "humanVersion": "I'm not sure what kind of pension I have. How can I find out, and why does it matter?", "aiOptimised": "I want to find out what type of pension, or pensions, I have. Please explain the main types in the UK (the State Pension, defined benefit pensions that pay an income based on salary and service, and defined contribution pensions that build up a pot), how I can tell which type each of mine is from my paperwork or by asking my employer or pension provider, and why the type matters for the choices I will have later. Include how I can trace a pension I have lost touch with.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon"], "topics": ["building_have","soon_get"] },
        { "id": "foundation_1", "quickSummary": "How much income to aim for", "humanVersion": "What should I aim for as a realistic monthly retirement income?", "aiOptimised": "I want to work out a realistic monthly income to aim for in retirement. Please explain what I should think about when setting a target (the lifestyle I want, housing costs, whether I am single or in a couple, rising prices and how long retirement may last), give illustrative monthly figures for a basic, a moderate and a comfortable standard of living in the UK from a recognised published source that you name, and show how I could turn these into a target of my own.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon"], "topics": ["building_need","soon_get"] },
        { "id": "foundation_7", "quickSummary": "What my pensions will pay", "humanVersion": "How much income will I get from the pensions I already have?", "aiOptimised": "I want to find out how much income I am likely to receive in retirement from the pensions I already have. Please explain where I can find a projection for each one (my State Pension forecast, the yearly statements from workplace and personal pensions, and any pension I have lost touch with), what those projections assume and why the real amount may differ, and how I can add them together into one monthly figure in today's money.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon"], "topics": ["building_have","soon_get"] },
        { "id": "foundation_2", "quickSummary": "The State Pension", "humanVersion": "How much State Pension can I expect to get?", "aiOptimised": "I want to know how much State Pension I can expect to receive. Please give the full rate of the new State Pension, explain how my National Insurance record decides how much of it I get (including the number of qualifying years needed for any pension and for the full amount), say when it can be claimed and how it rises each year, and tell me how to check my own forecast and whether I can fill gaps in my record.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon"], "topics": ["building_have","soon_get"] },
        { "id": "foundation_3", "quickSummary": "Turning a pension into income", "humanVersion": "What are my options for taking money from my pension, and what are the pros and cons of each?", "aiOptimised": "I want to understand the different ways I can turn my pension savings into retirement income. Please explain each main option in the UK: buying a guaranteed income for life (an annuity), keeping the money invested and drawing from it (drawdown), taking lump sums, leaving it where it is for now, and mixing these. For each one, give the main advantages and disadvantages, including how the tax-free part works, how secure the income is, and which choices cannot be reversed.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["soon"], "topics": ["soon_options"] },
        { "id": "foundation_5", "quickSummary": "How much I need to save", "humanVersion": "How big a pension pot do I need to give me the income I want?", "aiOptimised": "I want to work out how much pension savings I would need to reach my target retirement income. Please show a simple way to work backwards from a yearly income target to the size of pot needed, taking off the State Pension and any other income first. Explain the assumptions that change the answer most (how long the money must last, investment growth, rising prices and charges), give one short illustrative calculation with the steps shown, and say what the options are if there is a gap.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon"], "topics": ["building_need","soon_get"] },
        { "id": "foundation_8", "quickSummary": "What affects my pension", "humanVersion": "What decides how much pension I end up with, and which of those things can I change?", "aiOptimised": "I want to understand what will affect how much pension I get in retirement. Please explain the main factors: how much my employer and I pay in and for how long, tax relief, investment growth and charges, when I start taking it, my National Insurance record for the State Pension, and the rules of any pension based on salary and service. Say which of these I can influence and which I cannot, and how I can check where I stand now.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building"], "topics": ["building_have"] },
        { "id": "foundation_9", "quickSummary": "When I can take my pension", "humanVersion": "How old do I need to be before I can take money from my pension?", "aiOptimised": "I want to know when I can start taking my pension. Please explain the earliest age I can normally take money from a workplace or personal pension and any change to that age that is already planned, how a pension scheme's own normal retirement age can differ, when the State Pension starts and how I check my own State Pension age, and what taking a pension earlier or later can mean for how much I get.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon"], "topics": ["building_have","soon_options"] },
        { "id": "foundation_4", "quickSummary": "Planning with a partner", "humanVersion": "How can my partner and I work out our pensions and retirement income together?", "aiOptimised": "My partner and I want to plan our pensions and retirement income together. Please explain what we should look at as a couple: adding up what each of us is likely to get, what happens to each pension if one of us dies first, how using both of our tax allowances can affect the tax we pay, and what to think about if we retire at different times. Say how the rules differ for couples who are not married or in a civil partnership, and which paperwork we should keep up to date.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","taking"], "topics": ["building_change","taking_later"] }
      ]
    },
    {
      "id": "awareness",
      "title": "Things to consider",
      "subtitle": "Important factors that will impact your retirement strategy.",
      "questions": [
        { "id": "awareness_1", "quickSummary": "Not running out of money", "humanVersion": "How much can I take out of my pension each year and still make it last?", "aiOptimised": "I want to understand how much I could take from my pension pot each year without running out of money. Please explain what is meant by a sustainable withdrawal rate, the well-known rules of thumb and the assumptions and limits behind them, and what makes the right amount different for each person (age, pot size, how the money is invested, charges, rising prices and other income). Explain how reviewing withdrawals each year can help, and what the alternatives are for someone who needs more certainty.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["taking"], "topics": ["taking_last"] },
        { "id": "awareness_2", "quickSummary": "Stock market ups and downs", "humanVersion": "What happens to my pension income if the stock market falls?", "aiOptimised": "I want to understand what a fall in the stock market would mean for the income I take from my pension. Please explain why falls in the early years of taking money out do more damage than later falls, using one short illustration, and describe the common ways people reduce this risk (holding some cash, being flexible about withdrawals, spreading investments, or securing some guaranteed income), with the trade-offs of each.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["taking"], "topics": ["taking_last"] },
        { "id": "awareness_3", "quickSummary": "Rising prices", "humanVersion": "How will inflation affect my retirement income, and what can protect it?", "aiOptimised": "I want to understand how inflation, meaning rising prices, will affect my income in retirement and what can protect it. Please show how the buying power of a fixed income falls over a long retirement, explain which kinds of retirement income normally rise with prices and which do not (the State Pension, pensions based on salary and service, annuities and money left invested), and describe the main ways people protect their income, with the trade-offs of each.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","taking"], "topics": ["building_change","taking_last"] },
        { "id": "awareness_4", "quickSummary": "Paying for care", "humanVersion": "What might care cost when I am older, and how can I plan for it?", "aiOptimised": "I want to understand what long-term care might cost in later life and how people plan for it. Please give typical costs of care at home and in a care home in the UK, explain who pays (when the council or the NHS helps, how savings and my home are counted, and how the rules differ between England, Scotland, Wales and Northern Ireland), and describe the main ways people plan to meet the cost, with the trade-offs of each.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["taking"], "topics": ["taking_later"] },
        { "id": "awareness_5", "quickSummary": "Common mistakes to avoid", "humanVersion": "Where do people most often go wrong when planning their retirement income?", "aiOptimised": "I want to learn where people most often go wrong when planning their retirement income, so that I can avoid the same mistakes. Please give the five or six that matter most in the UK, such as underestimating how long retirement may last, ignoring rising prices, losing track of old pensions, taking money out without understanding the tax, and falling for scams. For each one, say briefly why it happens, what it can cost and how to avoid it.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon"], "topics": ["building_need","soon_sort"] },
        { "id": "awareness_6", "quickSummary": "If my plans change", "humanVersion": "What can I do if I have to retire early, my investments do badly, or I live much longer than I expected?", "aiOptimised": "I want to know what I can do if my retirement plans are knocked off course. Please cover three situations: having to stop work earlier than planned, my investments doing worse than expected, and living much longer than I expected. For each one, explain what it would mean for my income and the main options people have to adjust, with the trade-offs, and suggest how some flexibility can be built into a plan from the start.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon","taking"], "topics": ["building_change","soon_sort","taking_later"] },
        { "id": "awareness_7", "quickSummary": "Too ill to work", "humanVersion": "Can I take my pension early if my health means I have to stop working?", "aiOptimised": "I want to know what happens to my pension if I become too ill to work, and whether I can take it early. Please explain the rules that can let someone take a workplace or personal pension before the normal minimum age because of ill health, how serious ill health with a short life expectancy is treated differently, what the pension scheme will usually ask for, and what this means for the State Pension. Mention the benefits and other support worth checking, and what taking a pension early can mean for later income.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building"], "topics": ["building_change"] }
      ]
    },
    {
      "id": "optimise",
      "title": "Getting the most out of your pension",
      "subtitle": "Strategies to optimize your retirement income and tax efficiency.",
      "questions": [
        { "id": "optimise_7", "quickSummary": "Saving more", "humanVersion": "What do I gain by paying more into my pension, and what are the downsides?", "aiOptimised": "I want to understand the benefits of saving more into my pension. Please explain how tax relief and employer contributions add to what I pay in, how long-term growth makes earlier saving count for more, and show with one simple illustration the difference a small extra monthly amount could make. Also explain the limits and downsides: the yearly limit on tax-relieved saving, that the money is locked away until a minimum age, and that investments can fall as well as rise.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building"], "topics": ["building_need"] },
        { "id": "optimise_8", "quickSummary": "Tax on my pension", "humanVersion": "How much will I lose in tax when I take money from my pension?", "aiOptimised": "I want to understand how much tax I will pay on my pension. Please explain how much can usually be taken tax-free and how the rest is taxed as income, give the Personal Allowance and Income Tax bands (noting where Scotland differs), explain that the State Pension is taxable and how the tax on it is collected, and show one short illustration of the tax on a year's pension income. Include why a first withdrawal may be taxed at an emergency rate and how to claim it back.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["soon","taking"], "topics": ["soon_options","taking_tax"] },
        { "id": "optimise_2", "quickSummary": "Combining pension pots", "humanVersion": "I have more than one pension. What should I think about before putting them together?", "aiOptimised": "I have more than one pension pot and want to understand what to take into account before combining them. Please explain the possible benefits (easier to manage, perhaps lower charges or more choice), what I could lose by transferring (guaranteed benefits, protected terms, exit charges or employer payments), why pensions based on salary and service need particular care, and what I should ask each pension provider before deciding.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon"], "topics": ["building_need","soon_sort"] },
        { "id": "optimise_1", "quickSummary": "Paying less tax on my income", "humanVersion": "How can I take money from my pension and savings without paying more tax than I need to?", "aiOptimised": "I want to understand how to take income from my pensions and savings in a tax-efficient way. Please explain how each kind of income is taxed (pension withdrawals, the tax-free part of a pension, the State Pension, tax-free savings accounts and other savings), the main allowances that apply, how the order and timing of withdrawals can change the tax paid, and how taking taxable money flexibly from a pension can limit what I can pay in afterwards.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["taking"], "topics": ["taking_tax"] },
        { "id": "optimise_4", "quickSummary": "Buying a guaranteed income", "humanVersion": "How do I decide whether to use my pension to buy an income that lasts for life?", "aiOptimised": "I want to understand how to weigh up using some or all of my pension to buy a guaranteed income for life (an annuity). Please explain how it works and the main types (level or rising, single or joint, with or without a guarantee period), what affects the income offered (age, health, pot size and interest rates), how it compares with keeping the money invested, and the questions that help someone decide. Explain why shopping around matters and that the purchase cannot normally be reversed.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["soon","taking"], "topics": ["soon_options","taking_last"] },
        { "id": "optimise_5", "quickSummary": "Investing while taking money out", "humanVersion": "Once I start taking an income, how should the rest of my pension be invested?", "aiOptimised": "I want to understand how people approach investing while they are taking money out of their pension. Please explain how investing changes once I am drawing an income instead of building up savings, the roles that shares, bonds and cash usually play, how the balance between growth and stability affects how long the money may last, and why charges and regular reviews matter. Explain the trade-offs of the common approaches without telling me which to choose.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["taking"], "topics": ["taking_last"] }
      ]
    },
    {
      "id": "anythingElse",
      "title": "Anything else?",
      "subtitle": "Specific scenarios, alternative options, and other common queries.",
      "questions": [
        { "id": "anythingElse_4", "quickSummary": "Free help", "humanVersion": "Who can I talk to about my retirement options without paying?", "aiOptimised": "I want to know where I can get free, impartial guidance about my retirement income. Please explain what each of the main free services in the UK offers and who it is for, including MoneyHelper, Pension Wise, the Pension Tracing Service, the State Pension forecast on GOV.UK and Citizens Advice, how I contact or book each one and what to have ready beforehand. Explain the difference between guidance and regulated financial advice, and how to spot a scam posing as a free pension review.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon","taking"], "topics": ["help"], "archived": true },
        { "id": "anythingElse_5", "quickSummary": "Getting financial advice", "humanVersion": "How do I find an independent adviser I can trust, and what will it cost?", "aiOptimised": "I want to know how to find an independent financial adviser I can trust, and what it is likely to cost. Please explain the difference between independent and restricted advice, where I can search for advisers in the UK, how to check that a firm and an adviser are authorised, the usual ways advisers charge and what to ask about costs, and the questions worth asking at a first meeting. Explain what protection I have if things go wrong, and how to avoid cloned firms and other scams.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["building","soon","taking"], "topics": ["help"], "archived": true },
        { "id": "anythingElse_1", "quickSummary": "Using the value of my home", "humanVersion": "Could my home help pay for my retirement, for example by moving somewhere smaller or borrowing against it?", "aiOptimised": "I want to understand how I could use the value of my home to help fund my retirement. Please explain the main options (moving to a cheaper home, equity release through a lifetime mortgage or home reversion, and renting out a room), how each works and what it typically costs, and the effect each can have on what I leave behind and on means-tested benefits. Make clear which steps are hard or costly to undo, and what kind of specialist advice is required for equity release.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["soon","taking"], "topics": ["soon_sort","taking_tax"] },
        { "id": "anythingElse_2", "quickSummary": "Working in retirement", "humanVersion": "Can I carry on working part-time once I start taking my pension, and how would it affect my tax?", "aiOptimised": "I want to understand the rules and effects of working part-time while taking a pension. Please explain whether I can work and take a workplace, personal or State Pension at the same time, how my earnings and pension income are taxed together, when National Insurance stops, how taking taxable money flexibly from a pension pot can cut the amount I can still pay into pensions, and what putting off my State Pension would mean. Give one short illustration of the tax on combined income.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["soon","taking"], "topics": ["soon_sort","taking_tax"] },
        { "id": "anythingElse_3", "quickSummary": "Passing on my pension", "humanVersion": "What happens to my pension when I die, and will my family pay tax on it?", "aiOptimised": "I want to understand how pensions are treated for Inheritance Tax and what happens to them when I die. Please explain the current rules and any change that has been announced, giving the date it takes effect, how the tax on what my beneficiaries receive depends on my age when I die, who can inherit different types of pension, and what I should do to make sure my pension goes to the people I intend, such as keeping my nomination forms up to date.\n\nPlease open by saying this is general information, not regulated financial advice, then give a short summary before the detail. Use British English, UK rules and plain words, and do not repeat my request back to me. Use the current UK tax year, name it as two years with a slash, and tell me to check figures on GOV.UK. Use the rules as they are now, and mention any change already announced that takes effect within the next year, saying when. Say when you are unsure rather than guess, and state any assumptions. Do not recommend a specific product, provider, fund or course of action: explain the options and their trade-offs instead. Flag any step that cannot be undone, and mention pension scam warning signs where relevant. Keep the whole answer to this question between 250 and 500 words. End by pointing me to free, impartial guidance from MoneyHelper and Pension Wise and to a regulated financial adviser I can check on the FCA Register, then suggest one or two follow-up questions without answering them.", "stages": ["taking"], "topics": ["taking_later"] }
      ]
    }
  ]
};
