// Reference mirror of the question data. The live app reads PROMPTS_DATA inline
// in index.html's <script data-dc-script> block, not this file — keep both in sync.
const promptsData = {
  "sections": [
    {
      "id": "foundation",
      "title": "Foundations of a plan",
      "subtitle": "The essential building blocks everyone needs to understand first.",
      "questions": [
        { "id": "foundation_1", "quickSummary": "Target retirement income", "humanVersion": "What should I aim for as a realistic monthly retirement income, and what are the main ways people fund that?", "aiOptimised": "I'm planning my retirement income and need help understanding realistic targets. Please help me think through: (1) What factors should I consider when setting a monthly retirement income goal (e.g., current lifestyle, cost of living, inflation, longevity expectations)? (2) What is a realistic income target for different lifestyle scenarios (modest, comfortable, affluent)? (3) What are the main ways people fund retirement income (pension drawdown, annuities, investments, state benefits, part-time work, rental income)? For each funding method, explain the basic mechanics and typical contribution to overall income. Please be specific about UK context where relevant, and provide realistic examples of monthly income targets for different circumstances.", "stages": ["building","soon"], "styles": ["factual","caseStudy"] },
        { "id": "foundation_2", "quickSummary": "State Pension basics", "humanVersion": "How does the UK State Pension work, and how much can I realistically expect to receive?", "aiOptimised": "I need to understand the UK State Pension and how much I can expect from it. Please explain: (1) How does the modern UK State Pension system work (New State Pension vs. legacy systems)? (2) What factors determine the amount I'll receive (National Insurance contributions record, gaps in contributions, years worked)? (3) How much can I realistically expect (provide current rates and examples for different contribution histories)? (4) How do I check my own State Pension forecast? (5) What happens if I have gaps in my National Insurance record, and can they be filled? Please structure this for someone who doesn't understand pensions and provide specific 2025 figures where possible.", "stages": ["building","soon"], "styles": ["factual","simple"] },
        { "id": "foundation_3", "quickSummary": "Pension income mechanisms", "humanVersion": "What are the different ways I can turn my pension savings into retirement income — drawdown, annuity, or a combination — and what are the pros and cons of each?", "aiOptimised": "I need to understand the different ways to convert pension savings into retirement income. Please explain each option clearly: (1) Pension drawdown — how it works, flexibility, risks, and best-case/worst-case scenarios. (2) Annuity — what you get, security, irreversibility, and value factors. (3) Hybrid approaches — combining drawdown and annuity, staged annuity purchases, and phased retirement. (4) For each option, provide: key benefits, main risks, who it suits best, and realistic examples. (5) What questions should I ask myself to decide which approach fits my situation? Please assume I'm unfamiliar with these concepts and provide detailed explanations without jargon.", "stages": ["soon","taking"], "styles": ["caseStudy","factual"] },
        { "id": "foundation_4", "quickSummary": "Partner coordination", "humanVersion": "If I have a partner, how should we coordinate our pensions and retirement income across both of us?", "aiOptimised": "My partner and I are planning retirement together but we may retire at different ages or have different pension arrangements. Please help me understand: (1) What coordination strategies exist for couples with different retirement ages? (2) How do spouse/civil partner pensions work (death benefits, survivor pensions)? (3) What is the best order to claim State Pensions for both of us, and does one person's decision affect the other? (4) How should we coordinate drawing from pensions if we have different amounts saved? (5) What tax implications are there for couples, and how can we minimize joint tax? (6) Are there any key risks or pitfalls we should be aware of (e.g., survivor's pension not covering enough)? Please provide worked examples for couples retiring at different ages with different pension pots.", "stages": ["building","soon","taking"], "styles": ["caseStudy","simple"] },
        { "id": "foundation_5", "quickSummary": "Calculate required savings", "humanVersion": "How much pension savings do I actually need to achieve my target retirement income?", "aiOptimised": "I need to work out whether I have enough pension savings for my retirement income goal. Please walk me through: (1) What is the basic formula or approach for calculating required pension savings (working backwards from income target)? (2) What assumptions go into this calculation (life expectancy, investment returns, inflation, withdrawals)? (3) What is a realistic investment return assumption for pension money in drawdown (taking into account current conditions)? (4) How do I factor in State Pension, other income sources, and part-time work into this calculation? (5) Give me a practical worked example: assume I want £3,000/month net income at age 65, expect State Pension of £10,000/year from age 67, and plan to live to 95. How much pension savings would I need to have at 65? (6) What happens if my calculation shows a shortfall — what options do I have? Please show the step-by-step thinking.", "stages": ["building","soon"], "styles": ["factual"] }
      ]
    },
    {
      "id": "awareness",
      "title": "Things to consider",
      "subtitle": "Important factors that will impact your retirement strategy.",
      "questions": [
        { "id": "awareness_1", "quickSummary": "Safe withdrawal rate", "humanVersion": "How much can I safely withdraw each year from my pension without running out of money? What is the 'safe withdrawal rate'?", "aiOptimised": "I'm concerned about how much I can safely spend from my pension each year without running out of money in retirement. Please explain: (1) What is the 'safe withdrawal rate' and how is it calculated? (2) What are the most common safe withdrawal rate percentages (e.g., 4% rule) and what assumptions do they make? (3) What factors affect how much is 'safe' for my specific situation (pension pot size, age at retirement, expected lifespan, investment returns, inflation, withdrawal flexibility)? (4) How do I work out my personal safe withdrawal rate? (5) What happens if actual investment returns are lower than assumed — what's my contingency? (6) Should I adjust my withdrawals based on investment performance, and if so, how? Please explain the thinking step-by-step with practical examples. Assume I'm in the UK, retiring at 65, with a pension pot of £200,000, expecting to live to 95.", "stages": ["soon","taking"], "styles": ["factual"] },
        { "id": "awareness_2", "quickSummary": "Sequence of returns risk", "humanVersion": "What is 'sequence of returns risk' and how can I protect my pension from poor investment returns early in retirement?", "aiOptimised": "I want to understand sequence of returns risk and why it matters in retirement. Please explain: (1) What is 'sequence of returns risk' and why is it a bigger problem in retirement than during working years? (2) Give a specific example showing how two people with identical pension pots and identical average returns can end up with very different outcomes based on when returns occur. (3) What is the 'critical period' and why is it important? (4) What strategies exist to protect against sequence risk (cash buffers, portfolio diversification, flexible spending, annuities, bucketing strategies)? (5) For each strategy, explain how it works and what trade-offs it involves. (6) If I'm entering drawdown in 2025-2026, how concerned should I be about current market conditions? Please provide practical examples and actionable strategies I can implement.", "stages": ["soon","taking"], "styles": ["caseStudy","factual"] },
        { "id": "awareness_3", "quickSummary": "Inflation impact", "humanVersion": "How much should I expect inflation to reduce my purchasing power, and what strategies protect against it?", "aiOptimised": "I'm worried that inflation will erode my retirement income over time. Please help me understand: (1) What is a realistic long-term inflation assumption for planning purposes (historical rates vs. current conditions)? (2) How much will my purchasing power decline over a 30-year retirement at different inflation rates? (3) What is the difference between nominal returns (what the numbers say) and real returns (what you can actually buy), and why does it matter? (4) What strategies protect against inflation (inflation-linked annuities, equity-heavy portfolios, adjusting spending, part-time work)? (5) For each strategy, explain the benefits and trade-offs. (6) How should I think about this if I'm receiving defined benefit pension income (which may or may not be inflation-protected)? Please provide a worked example showing purchasing power loss over 30 years at 2.5%, 3%, and 4% inflation, and recommend a practical mix of inflation protection strategies.", "stages": ["building","soon","taking"], "styles": ["factual","simple"] },
        { "id": "awareness_4", "quickSummary": "Long-term care costs", "humanVersion": "What are the potential costs of long-term care in later life, and how can I plan financially to cover them?", "aiOptimised": "I'm concerned about how long-term care costs might affect my retirement plan. Please explain: (1) What are realistic costs for different levels of care (home care, residential care, nursing care) in the UK today? (2) How do these costs vary by region and quality of care? (3) What are the different care funding scenarios (self-funded, means-tested support, care cap)? (4) How do I estimate the likelihood and timing of needing care (age, health status factors)? (5) What strategies exist to protect against catastrophic care costs (insurance, pre-funding, downsizing, family support, local authority support)? (6) For each strategy, what are the pros, cons, and costs? (7) Should I assume I need to set aside money for care now, and if so, how much? Please provide a worked example of someone needing 3 years of residential care starting at age 82, and show different funding options and their impact on retirement income.", "stages": ["soon","taking"], "styles": ["caseStudy","factual"] },
        { "id": "awareness_5", "quickSummary": "Common retirement mistakes", "humanVersion": "What are the most common mistakes people make when planning for retirement income, and how can I avoid them?", "aiOptimised": "I want to learn from others' mistakes when planning retirement income. Please explain: (1) What are the 10-15 most common mistakes people make (e.g., not accounting for inflation, underestimating care costs, poor investment decisions, tax inefficiency, not coordinating with partner)? (2) For each mistake, explain: why people make it, what the consequences typically are, and how to avoid it. (3) Which mistakes are most costly (in terms of money lost or retirement delayed)? (4) Which mistakes do people regret most, and why? (5) Are there different mistakes that commonly trip up people at different income levels? Please frame this as 'lessons learned' from real situations, be specific about financial impact where possible, and provide checklists for avoiding the major pitfalls.", "stages": ["building","soon"], "styles": ["caseStudy","simple"] },
        { "id": "awareness_6", "quickSummary": "Contingency planning", "humanVersion": "What should I do if circumstances change — if I need to retire earlier, investments underperform, or I live much longer than expected?", "aiOptimised": "I want to build flexibility into my retirement plan in case circumstances change. Please explain: (1) What are the main scenarios that could disrupt my retirement plan (forced early retirement due to health/redundancy, investment underperformance, living much longer than expected, inflation higher than assumed)? (2) For each scenario, what are my options to recover (delay claiming pensions, adjust spending, work part-time, use property equity, review investments)? (3) How much early retirement would cost me — what income reduction might I face if I had to stop work 2-5 years earlier? (4) If investments underperform for 5 years after I retire, what happens to my plan, and what should I do? (5) How should I design my pension allocation and withdrawal strategy to have 'outs' if things go wrong? (6) What's the minimum I could live on if needed, and how would I adjust? Please provide specific action plans for 3-4 realistic scenarios with numbers, and recommend a resilient strategy that handles multiple risks.", "stages": ["building","soon","taking"], "styles": ["caseStudy","factual"] }
      ]
    },
    {
      "id": "optimise",
      "title": "Getting the most out of your pension",
      "subtitle": "Strategies to optimize your retirement income and tax efficiency.",
      "questions": [
        { "id": "optimise_1", "quickSummary": "Tax-efficient withdrawal strategy", "humanVersion": "How can I take income from my pension and savings in a tax-efficient way? What is the best order to draw from different accounts, and how do I maximize tax-free allowances and my tax-free lump sum?", "aiOptimised": "I need to understand how to withdraw income from my retirement savings in a tax-efficient way. Please walk me through: (1) What are the main types of accounts I might have (pension, ISA, general savings, investment accounts, property) and how is income from each taxed differently? (2) What are the current tax-free allowances I should be aware of in 2025 (personal allowance, dividend allowance, capital gains allowance, trading allowance, pension allowance)? (3) In what order should I draw from different accounts to minimize tax over my lifetime (sequencing strategy)? (4) How should I time taking my pension tax-free lump sum (all at once vs. in stages over years) and why does timing matter for tax? (5) How does taking pension income affect my tax position for other income sources (state pension, rental income, dividends)? (6) Give me a practical worked example: I'm retiring at 65 with £200k pension, £50k ISA, £30k general savings, and will receive £10k state pension. How should I structure withdrawals year 1-5 to minimize tax? Please show the year-by-year breakdown and total tax paid under different strategies.", "stages": ["soon","taking"], "styles": ["factual","caseStudy"] },
        { "id": "optimise_2", "quickSummary": "Pension consolidation", "humanVersion": "Should I consolidate my multiple pensions into one plan, or keep them separate? What are the trade-offs?", "aiOptimised": "I have multiple pensions from different employers and I'm considering whether to consolidate them. Please explain: (1) What are the main reasons to consolidate pensions (simplicity, fees, investment choice, withdrawal flexibility)? (2) What are the main reasons to keep pensions separate (protection, different pension types, special terms, simplicity in some cases)? (3) What are the practical steps to consolidate (transfer process, timelines, costs)? (4) What risks exist in consolidation (transfer delays, loss of guarantees, pension transfers to unsuitable funds)? (5) What questions should I ask my existing pension providers before transferring (fees, investment options, death benefits, guarantees, withdrawal terms)? (6) For someone with 4-5 smaller pensions from previous jobs, what's the typical impact on fees and investment flexibility? Please provide a worked example showing the cost/benefit analysis of consolidating vs. keeping separate, and a decision-making flowchart for someone uncertain.", "stages": ["building","soon"], "styles": ["factual","simple"] },
        { "id": "optimise_3", "quickSummary": "DB and DC coordination", "humanVersion": "If I have both a defined benefit (final salary) pension and defined contribution pensions, how should I coordinate them?", "aiOptimised": "I have both a defined benefit (DB) pension from an old employer and defined contribution (DC) pensions from other roles. Please help me think this through: (1) What are the key differences between DB and DC pensions (guaranteed income vs. pot-based, investment risk, flexibility, death benefits)? (2) What is my strategy for claiming them — should I claim DB first and leave DC untouched, claim both in parallel, or some other approach? (3) How does claiming one type affect taxation or means-testing of the other? (4) How do the death benefits differ, and does this affect my strategy? (5) Should I consider taking a transfer value on the DB pension (if available) and consolidating into DC — what are the pros and cons? (6) How should my overall investment strategy account for having 'guaranteed' DB income plus variable DC income? Please provide examples for someone with (a) small DB pension + larger DC pot, (b) generous DB pension + small DC, and (c) roughly equal amounts, showing withdrawal strategies for each.", "stages": ["soon","taking"], "styles": ["caseStudy","factual"] },
        { "id": "optimise_4", "quickSummary": "Annuity decision point", "humanVersion": "At what point does buying an annuity make financial sense, and should it be part of my overall strategy?", "aiOptimised": "I'm trying to decide whether an annuity makes financial sense for me. Please explain: (1) What is an annuity and how does it work (payment structure, guarantees, death benefits, types — fixed, escalating, joint life)? (2) How much income would I get from different types of annuities, and how do annuity rates compare to historical levels? (3) What are the break-even points — at what age does an annuity typically make financial sense (life expectancy, discount rates)? (4) What are the key factors that affect whether an annuity suits my situation (health, life expectancy, other income sources, bequest goals, risk tolerance)? (5) What are the alternatives to a full annuity (drawdown, hybrid approaches, delayed annuity purchase, longevity insurance)? (6) If I buy an annuity, what type would suit me best (fixed, escalating, joint-life)? (7) What are the latest annuity rates (2025) and how have they changed? Please provide a detailed comparison for someone turning 65 with £150k pension pot — show annuity income vs. drawdown income over different scenarios (living to 80, 85, 90, 95), including tax implications.", "stages": ["soon","taking"], "styles": ["factual","caseStudy"] },
        { "id": "optimise_5", "quickSummary": "Investment strategy for drawdown", "humanVersion": "How should my investment strategy change as I move from accumulation to living off my pension? What portfolio type is appropriate?", "aiOptimised": "I need to rethink my investment strategy now that I'm retiring and will be drawing income. Please explain: (1) Why does investment strategy need to change from accumulation (saving) to decumulation (drawing income)? (2) What are the main portfolio types for retirement (cautious, balanced, growth, etc.) and who does each suit? (3) What should my asset allocation be (stocks vs. bonds vs. cash) and does it depend on my age, life expectancy, or income needs? (4) How important is ongoing growth in retirement — shouldn't I be 100% in safe investments? (5) What role should bonds play, and what duration should I target? (6) How much cash should I hold, and how does this relate to sequence of returns risk? (7) What about defensive/alternative investments, and do they help? (8) Should my portfolio change over time (getting more cautious as I age), and if so, how? Please provide specific portfolio allocation recommendations for someone aged 60-70, 70-80, and 80+ retiring with different income needs and risk tolerances. Include discussion of current yield and growth prospects (2025 context).", "stages": ["building","soon","taking"], "styles": ["factual","caseStudy"] },
        { "id": "optimise_6", "quickSummary": "Part-time work impact", "humanVersion": "How does part-time work in early retirement affect my pension tax, state pension eligibility, and overall income strategy?", "aiOptimised": "I'm considering part-time work in early retirement and need to understand the implications. Please explain: (1) How does earning additional income affect my tax position (personal allowance, higher rate tax, National Insurance)? (2) If I have both pension income and earned income, how does this affect my overall tax bill (different allowances, marginal rates)? (3) Can earning money reduce my State Pension (does it mean deferring is worse value)? (4) What is the 'earnings limit' for benefits or means-testing, and does any apply to me? (5) What income level starts to make additional tax bands relevant? (6) What are the National Insurance implications of part-time work (do I pay NI, does it affect my NI record, do I care)? (7) How much part-time work 'pays for itself' after tax and National Insurance? (8) Should I structure any work differently (employed vs. self-employed, consulting vs. salary)? Please provide worked examples: someone aged 62 earning £200/week, someone aged 60 earning £300/week, and someone aged 58 earning £500/week — for each show total tax/NI paid and net income received. Also show how this affects their retirement income needs from pension.", "stages": ["soon","taking"], "styles": ["factual","caseStudy"] }
      ]
    },
    {
      "id": "anythingElse",
      "title": "Anything else?",
      "subtitle": "Specific scenarios, alternative options, and other common queries.",
      "questions": [
        { "id": "anythingElse_1", "quickSummary": "Property wealth", "humanVersion": "How can I use my property wealth (e.g., downsizing or equity release) to fund retirement?", "aiOptimised": "I want to understand how I could use property wealth to support my retirement income. Please explain: (1) What are the main ways to release property wealth in retirement (downsizing, equity release/lifetime mortgages, home reversion plans, renting out a room)? (2) How does each option work, and what are the typical costs, interest, or reduction in property value involved? (3) What are the pros and cons of each approach, including the impact on any inheritance I want to leave and on means-tested benefits? (4) How do I estimate how much income or lump sum I could realistically release from my property? (5) What questions should I ask a specialist adviser before proceeding with any option? Please provide a worked example for someone with £200,000 of property equity comparing downsizing versus equity release." },
        { "id": "anythingElse_2", "quickSummary": "Working in retirement", "humanVersion": "What are the rules and implications of working part-time while drawing a pension?", "aiOptimised": "I'm considering working part-time while also drawing my pension and want to understand the implications. Please explain: (1) Can I work and draw a pension at the same time, and are there any restrictions on doing so? (2) How does earning income affect my tax position when combined with pension income (personal allowance, higher-rate tax thresholds)? (3) What is the Money Purchase Annual Allowance (MPAA), and when does it apply if I start flexibly drawing from a defined contribution pension while still working? (4) Does part-time work affect my State Pension or entitlement to any other benefits? (5) What National Insurance considerations apply to part-time earnings at this stage? Please provide a worked example of someone earning £10,000/year part-time alongside £15,000/year of pension income, showing the tax and allowance implications." },
        { "id": "anythingElse_3", "quickSummary": "Inheritance & estate", "humanVersion": "How are pensions treated for inheritance tax purposes?", "aiOptimised": "I want to understand how my pension fits into inheritance planning. Please explain: (1) Are pensions normally inside or outside of my estate for inheritance tax purposes? (2) How does the tax treatment differ depending on whether I die before or after age 75? (3) Who can inherit my pension, and how is it taxed in their hands? (4) What practical steps do I need to take to make sure my pension goes to the people I intend (e.g., expression of wish forms, keeping beneficiaries up to date)? (5) How might proposed or recent changes to pension and inheritance tax rules affect this? Please explain in plain English, note clearly where rules may change, and suggest what I should confirm directly with a financial adviser or my pension provider." }
      ]
    }
  ]
};
